### ISSUE TITLE
VS Code Output: onnection to lsp times out

### ISSUE THREAD

**Issue by validset** [ailisp/commonlisp-vscode#14]
Hey there, new to lisp and vscode.

Got just about everything installed on your guide, 

performed all the tasks listed except the first one listed which looks optional.
- cl-lsp is updated with a cleaner REPL! Please update by do git pull in ~/.roswell/local-projects/ailisp/cl-lsp

Everything is looking good, added the ~/.roswell/bin, however!

The following shows in the output window:
[Error - 6:29:43 PM] Starting client failed
Error: Connection to lsp times out
	at Timeout._onTimeout (/home/tr/.vscode/extensions/ailisp.commonlisp-vscode-0.3.2/out/extension.js:137:32)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)

and VS Code is chain displaying terminal process "/home/tr/.roswell/bin/cl-lsp 'tcp,' '10003'" terminated wiht exit code 1.

What does that mean? i am new new to lisp and vs code.

Thanks, i look forward to having a nice interface like VS code and repl interaction.

Nick.

**Comment by cardboardboxpepe** [comment]
I'm getting the same error, not sure what it is. I looked into executing cl-lsp manually thru a terminal and it says:

```
;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "%CODE-ENTRY-POINTS" not found in the SB-KERNEL package.
;
;       Line: 1100, Column: 56, File-Position: 43455
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/dev/.roswell/lisp/quicklisp/dists/quicklisp/software/conium-20200218-git/sbcl.lisp" {1004D9B8B3}>
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {1004A704B3}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "conium" "sbcl">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1004A704B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10026AFC33}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10026AFC33}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10026AFC33}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "conium" "sbcl">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "conium" "sbcl">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "conium" "sbcl">)
6: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
7: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "conium" "sbcl">) [fast-method]
8: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002E68373}>) [fast-method]
9: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
10: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002E68373}>) [fast-method]
11: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "prepl"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
12: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "prepl"> :VERBOSE NIL)
13: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
14: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "prepl"> :VERBOSE NIL) [fast-method]
15: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "prepl" :VERBOSE NIL)
16: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "prepl" :VERBOSE NIL) [fast-method]
18: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002E656DB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002E5ED3B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "prepl" :VERBOSE NIL) [fast-method]
22: (ASDF/OPERATE:LOAD-SYSTEM "prepl" :VERBOSE NIL)
23: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1002E5EC8B}>)
24: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "prepl" :PROMPT NIL)
25: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002E40B9B}>) [fast-method]
26: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1004F3CD53}> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1002E40B9B}>) [fast-method]
27: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) (:CL-LSP :PREPL :LINEDIT) :PROMPT NIL :SILENT T :VERBOSE NIL) [fast-method]
28: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100344FDCB}>)
29: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (:CL-LSP :PREPL :LINEDIT)) :SILENT T) #<NULL-LEXENV>)
30: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (:CL-LSP :PREPL :LINEDIT)) :SILENT T)) #<NULL-LEXENV>)
31: (EVAL-TLF (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (:CL-LSP :PREPL :LINEDIT)) :SILENT T)) NIL NIL)
32: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (:CL-LSP :PREPL :LINEDIT)) :SILENT T)) NIL)
33: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/dev/.roswell/bin/./cl-lsp" {10033AE223}> #<SB-IMPL::STRING-INPUT-STREAM {1005094BD3}>) {10033B5BA3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
34: ((FLET SB-FASL::THUNK :IN LOAD))
35: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (FLET SB-FASL::THUNK :IN LOAD) {7F2BBCE475DB}> #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/dev/.roswell/bin/./cl-lsp" {10033AE223}> #<SB-IMPL::STRING-INPUT-STREAM {1005094BD3}>) {10033B5BA3}>)
36: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/dev/.roswell/bin/./cl-lsp" {10033AE223}> #<SB-IMPL::STRING-INPUT-STREAM {1005094BD3}>) {10033B5BA3}> NIL)
37: (LOAD #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /home/dev/.roswell/bin/./cl-lsp" {10033AE223}> #<SB-IMPL::STRING-INPUT-STREAM {1005094BD3}>) {10033B5BA3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
38: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /home/dev/.roswell/bin/./cl-lsp" {10033AE223}>)
39: (ROSWELL:SCRIPT "./cl-lsp" "tcp" "10003")
40: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "./cl-lsp" "tcp" "10003") (:QUIT NIL)))
41: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "./cl-lsp" "tcp" "10003") (:QUIT NIL)))) #<NULL-LEXENV>)
42: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "./cl-lsp" "tcp" "10003") (:QUIT NIL)))))
43: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"./cl-lsp\"\"tcp\"\"10003\")(:quit ())))")))
44: (SB-IMPL::TOPLEVEL-INIT)
45: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
46: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
47: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
;
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
```
Maybe that gives you some insight into the problem. Any help in resolving this issue would be appreciated.

**Comment by SonyaHon** [comment]
Up. Same error for me with MacOS BigSur

**Comment by cardboardboxpepe** [comment]
I fixed this error with reverting to an older version of SBCL on Roswell. The version I'm running is 2.0.11
